/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-13 06:55:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\">\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#loginBtn\").click(function() {\r\n");
      out.write("			if ($(\"#userid\").val() == \"\") {\r\n");
      out.write("				alert(\"아이디를 입력하세요.\")\r\n");
      out.write("				$(\"#userid\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} //userid\r\n");
      out.write("			if ($(\"#pwd\").val() == \"\") {\r\n");
      out.write("				alert(\"비밀번호를 입력하세요.\")\r\n");
      out.write("				$(\"#pwd\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}//pwd\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				url : \"loginPro.jsp\",\r\n");
      out.write("				data : {\r\n");
      out.write("					userid : $(\"#userid\").val(),\r\n");
      out.write("					pwd : $(\"#pwd\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(resp) {\r\n");
      out.write("				// 일반회원 memberView.jsp, 관리자는 memberList.jsp로 접속\r\n");
      out.write("				if(resp.trim()==0){\r\n");
      out.write("					alert(\"일반회원 로그인 성공\");\r\n");
      out.write("					// location.href=\"memberList.jsp\";\r\n");
      out.write("					$(location).attr(\"href\",\"memberView.jsp\");\r\n");
      out.write("				}else if(resp.trim()==1){\r\n");
      out.write("					alert(\"관리자 로그인 성공\");\r\n");
      out.write("					$(location).attr(\"href\",\"memberList.jsp\");\r\n");
      out.write("				}else if(resp.trim()==-1){\r\n");
      out.write("					alert(\"회원이 아닙니다. 회원가입하세요.\");\r\n");
      out.write("				}else if(resp.trim()==2){\r\n");
      out.write("					alert(\"비밀번호 오류 비밀번호를 확인하세요\");					\r\n");
      out.write("				}\r\n");
      out.write("			},\r\n");
      out.write("				error : function(e) {\r\n");
      out.write("					alert(e + \": error\")\r\n");
      out.write("				}\r\n");
      out.write("			})//ajax\r\n");
      out.write("		})//loginBtn\r\n");
      out.write("	})//document\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container mt-5\">\r\n");
      out.write("		<div align=\"right\">\r\n");
      out.write("			<a href=\"memberForm.jsp\">회원가입</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<h2>로그인</h2>\r\n");
      out.write("		<form action=\"\" id=\"frm\" method=\"post\">\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"userid\">UserID:</label> <input type=\"text\"\r\n");
      out.write("					class=\"form-control\" id=\"userid\" placeholder=\"Enter Your UserID\"\r\n");
      out.write("					name=\"userid\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label for=\"pwd\">Password:</label> <input type=\"text\"\r\n");
      out.write("					class=\"form-control\" id=\"pwd\"\r\n");
      out.write("					placeholder=\"Enter Your Password\" name=\"pwd\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<button type=\"button\" class=\"btn btn-primary\" id=\"loginBtn\">로그인</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
